FROM node:lts-alpine
ENV NODE_ENV=production
WORKDIR /usr/src/app
RUN useradd -u 1234 micro
USER micro
COPY ["package.json", "package-lock.json*","./"]
# COPY ["package.json", "package-lock.json*"]
RUN npm install 
# RUN npm install --production --silent && mv node_modules ../
COPY . .
EXPOSE 3000
# RUN chown -R node /usr/src/app
# USER node
CMD ["npm", "start"]


