FROM node:lts
ENV NODE_ENV=production
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*","./"]
RUN npm install  --only=production
COPY . .

FROM node:lts-alpine
COPY --from=0 /usr/src/app .
RUN apk add nginx sudo openrc --no-cache 
COPY micro.conf /etc/nginx/conf.d/default.conf
RUN adduser -D micro
USER micro
EXPOSE 3000
ENTRYPOINT ["./docker/entrypoint.sh"]